// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Grouper 2",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Grouper 2",
            targets: ["AppModule"],
            bundleIdentifier: "Shawnwang.Grouper-2",
            teamIdentifier: "586L2Q38YL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readOnly),
                .camera(purposeString: "This app uses your camera to group by detecting faces. All operations are performed offline on your device."),
                .photoLibrary(purposeString: "This app accesses your photo library to allow you to select a picture and group the people on the picture. This app also saves finished group assignments as pictures. All operations are performed offline on your device.")
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(url: "https://github.com/simibac/ConfettiSwiftUI.git", "1.1.0"..<"2.0.0"),
        .package(url: "https://github.com/swiftcsv/SwiftCSV.git", "0.9.1"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui"),
                .product(name: "SwiftCSV", package: "swiftcsv")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
